apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: petbro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: petbro-authservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: authservice
            - name: SERVICE_PORT
              value: "8080"
            - name: APP_ENV
              value: prod
            - name: APP_VERSION
              value: "1.0.0"
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: json
            - name: LOG_OUTPUT
              value: stdout
            - name: LOG_FILE_PATH
              value: /tmp/authservice.log
            - name: LOG_ERROR_FILE_PATH
              value: /tmp/authservice-error.log
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: auth_service
            - name: USER_SERVICE_BASE_URL
              value: http://userservice:8081
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
