apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: petbro
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: petbro-authservice
        static_configs:
          - targets:
              - authservice:8080

      - job_name: petbro-userservice
        static_configs:
          - targets:
              - userservice:8081

      - job_name: petbro-friendservice
        static_configs:
          - targets:
              - friendservice:8082

      - job_name: petbro-frontend
        static_configs:
          - targets:
              - frontend:80
