global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: userservice
    metrics_path: /metrics
    static_configs:
      - targets: ["userservice:8081"]

  - job_name: authservice
    metrics_path: /metrics
    static_configs:
      - targets: ["authservice:8080"]

  - job_name: friendservice
    metrics_path: /metrics
    static_configs:
      - targets: ["friendservice:8082"]
